### PR TITLE
Try out specs2 4.14.1-cross

### PR DESCRIPTION
**Pull request by armanbilge**
No idea how we can version this. Anyway, a snapshot of this would be great so we can try it out in CE :)

### CODE REVIEW

**Comment by vasilmkd** [comment]
Is this version built on Scala 3.1.1? I've been wanting to release both `discipline` and `discpline-specs2` on Scala 3.1.1 and all platforms.

**Comment by armanbilge** [comment]
Yes. We can do it! We just need https://github.com/typelevel/scalacheck/pull/879 :)

**Comment by gwils** [comment]
A release based on this would really help my team!

**Comment by vasilmkd** [comment]
I cherry picked the changes to a new [branch](https://github.com/typelevel/discipline-specs2/tree/specs2-cross-build) and the snapshot release is `1.5-69548db-SNAPSHOT`.

**Pull request closed without merging**
